# https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml
# README FIRST
# 1. replace "NAMESPACE" and "COLLECTION_NAME" with the correct name in the env section (e.g. with 'community' and 'mycollection')
# 2. If you don't have unit tests remove that section
# 3. If your collection depends on other collections ensure they are installed, see "Install collection dependencies"
# If you need help please ask in #ansible-community on the Libera.chat IRC network

name: Linting
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - devel
    paths:
      - 'roles/**'
      - 'playbooks/**'
  pull_request:
    branches:
      - main
      - devel
    paths:
      - 'roles/**'
      - 'playbooks/**'

env:
  NAMESPACE: thorian93
  COLLECTION_NAME: web 

jobs:

  linting:
    runs-on: ubuntu-latest
    name: Run Linting

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Run yamllint on roles
        run: yamllint -c .yamllint roles/
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Run yamllint on playbooks
        run: yamllint -c .yamllint playbooks/
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Run ansible-lint on roles
        run: ansible-lint -c  ${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/.ansible-lint ${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/roles/
        working-directory: ./ansible_collections/
        env:
          ANSIBLE_ROLES_PATH: "./thorian93/main/roles"

      - name: Run ansible-lint on playbooks
        run: ansible-lint -c  ${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/.ansible-lint ${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/playbooks/
        working-directory: ./ansible_collections/
        env:
          ANSIBLE_ROLES_PATH: "./thorian93/main/roles"
