# https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml
# README FIRST
# 1. replace "NAMESPACE" and "COLLECTION_NAME" with the correct name in the env section (e.g. with 'community' and 'mycollection')
# 2. If you don't have unit tests remove that section
# 3. If your collection depends on other collections ensure they are installed, see "Install collection dependencies"
# If you need help please ask in #ansible-community on the Libera.chat IRC network

name: Molecule Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - devel
    paths:
      - 'roles/**'
  push:
    branches:
      - main
      - devel
    paths:
      - 'roles/**'

env:
  NAMESPACE: thorian93
  COLLECTION_NAME: web 

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Run Molecule
    strategy:
      fail-fast: false
      matrix:
        role:
          - webserver

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: Test with molecule
        run: |
          cd roles/${{ matrix.role }}
          molecule test -d docker
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
