---
name: Release
on: # yamllint disable-line rule:truthy
  workflow_dispatch:

env:
  FILES: "CHANGELOG.rst LICENSE README.md ansible.cfg galaxy.yml"
  DIRS: "changelogs meta playbooks roles"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current version
        id: current_version
        run: echo "version=$(grep 'version:' galaxy.yml | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      #
      # First stage: Build and install collection to generate docs and changelogs.
      #

      - name: Copy Files and Directories to Source
        run: |
          mkdir -p build/src
          cp $files build/src
          cp -rf $directories build/src
        env:
          files: ${{env.FILES}}
          directories: ${{env.DIRS}}

      - name: Build Ansible Collection
        run: ansible-galaxy collection build build/src --force

      - name: Install Ansible Collection
        run: ansible-galaxy collection install ./thorian93-web-${{ steps.current_version.outputs.version }}.tar.gz

      - name: Compile Collection Changelog
        run: antsibull-changelog release

      - name: Create Pull Request for docs and changelog against devel branch
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update Changelogs
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: changelogs-update-${{ steps.current_version.outputs.version }}
          base: devel
          delete-branch: true
          title: '[Auto] Update changelogs for ${{ steps.current_version.outputs.version }}'
          body: |
            Changelogs updated during *${{ steps.current_version.outputs.version }}* release.
          assignees: thorian93
          reviewers: thorian93
          draft: false

      #
      # Second stage: Build the final version of the collection and release it.
      #

      - name: Copy Files and Directories to Source
        run: |
          mkdir -p build/src
          cp $files build/src
          cp -rf $directories build/src
          rm -rf build/src/roles/*/molecule
        env:
          files: ${{env.FILES}}
          directories: ${{env.DIRS}}

      - name: Build Ansible Collection
        run: ansible-galaxy collection build build/src --force

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.current_version.outputs.version }}
          release_name: ${{ steps.current_version.outputs.version }}
          body: |
            # Ansible Collection: thorian93.web

            For information about this collection and how to install it, refer to the [README](https://github.com/thorian93/web/blob/web/README.md).
            
            For a detailed changelog, refer to the [CHANGELOG](https://github.com/thorian93/web/blob/web/CHANGELOG.rst).
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: thorian93-web-${{ steps.current_version.outputs.version }}.tar.gz
          asset_name: thorian93-web-${{ steps.current_version.outputs.version }}.tar.gz
          asset_content_type: application/tar+gzip

      - name: Publish Ansible Collection to the Galaxy
        run: ansible-galaxy collection publish thorian93-web-${{ steps.current_version.outputs.version }}.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
